{% set setup_data = load_setup_py_data() %}
package:
  name: bamaligncleaner
  version: {{ setup_data['version'] }}

source:
  git_rev: {{ setup_data['version'] }}
  git_url: https://github.com/maxibor/bamaligncleaner.git

build:
  number: 0
  skip: true  # [win and py27 or win32]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - click >=7.0
    - tqdm
    - bioconda::pysam >=0.15.2
    
test:
  imports:
    - bamaligncleaner


about:
  home: https://github.com/maxibor/bamaligncleaner
  license: GPL-3.0
  summary: 'Removes unaligned references in BAM alignment file'

# Build using: conda build -c conda-forge .
